db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/esportify?serverTimezone=UTC
db.user=root
db.password=

# Streaming live APIs
streaming.youtube.api_key=AIzaSyBZ4FUI1FZfuDLbckYitcmW7Gfs07PJIBI
streaming.youtube.live_query=esports live
streaming.youtube.highlights_query=esports highlights
