import argparse
import csv
import json
import math
import pickle
from datetime import date, datetime, timedelta
from pathlib import Path


WINDOWS = (1, 3, 7, 14, 30)
MODEL_FILE = "payment_forecast_model.pkl"
METADATA_FILE = "payment_forecast_metadata.json"


def parse_args():
    parser = argparse.ArgumentParser(description="Train payment revenue forecast model.")
    parser.add_argument("--dataset", required=True, help="CSV generated by PaymentForecastTrainCommand.")
    parser.add_argument("--artifact-dir", required=True, help="Directory for model and metadata artifacts.")
    return parser.parse_args()


def load_series(dataset_path):
    rows = []
    with open(dataset_path, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows.append(
                {
                    "date": datetime.strptime(row["date"], "%Y-%m-%d").date(),
                    "revenue": float(row["revenue"]),
                    "paid_orders": int(row["paid_orders"]),
                    "failed_orders": int(row["failed_orders"]),
                    "total_orders": int(row["total_orders"]),
                }
            )

    if not rows:
        today = date.today()
        rows.append({"date": today, "revenue": 0.0, "paid_orders": 0, "failed_orders": 0, "total_orders": 0})

    rows.sort(key=lambda item: item["date"])
    return rows


def window_sum(rows, index, key, window):
    start = max(0, index - window + 1)
    return sum(item[key] for item in rows[start : index + 1])


def build_dataset(rows):
    features = []
    targets = []
    for index, row in enumerate(rows):
        max_horizon = 30
        if index + max_horizon >= len(rows):
            break

        feature_row = [
            row["date"].weekday(),
            row["date"].day,
            row["date"].month,
            row["date"].isocalendar().week,
        ]
        for window in WINDOWS:
            feature_row.extend(
                [
                    window_sum(rows, index, "revenue", window),
                    window_sum(rows, index, "paid_orders", window),
                    window_sum(rows, index, "failed_orders", window),
                    window_sum(rows, index, "total_orders", window),
                ]
            )

        future_1 = rows[index + 1 : index + 2]
        future_7 = rows[index + 1 : index + 8]
        future_30 = rows[index + 1 : index + 31]
        targets.append(
            [
                sum(item["revenue"] for item in future_1),
                sum(item["revenue"] for item in future_7),
                sum(item["revenue"] for item in future_30),
                sum(item["paid_orders"] for item in future_1),
                sum(item["paid_orders"] for item in future_7),
                sum(item["paid_orders"] for item in future_30),
            ]
        )
        features.append(feature_row)

    return features, targets


def latest_features(rows):
    index = len(rows) - 1
    row = rows[index]
    feature_row = [
        (row["date"] + timedelta(days=1)).weekday(),
        row["date"].day,
        row["date"].month,
        row["date"].isocalendar().week,
    ]
    for window in WINDOWS:
        feature_row.extend(
            [
                window_sum(rows, index, "revenue", window),
                window_sum(rows, index, "paid_orders", window),
                window_sum(rows, index, "failed_orders", window),
                window_sum(rows, index, "total_orders", window),
            ]
        )
    return [feature_row]


def heuristic_forecast(rows):
    recent = rows[-7:]
    previous = rows[-14:-7] if len(rows) >= 14 else []
    recent_revenue = sum(item["revenue"] for item in recent) / max(1, len(recent))
    previous_revenue = sum(item["revenue"] for item in previous) / max(1, len(previous)) if previous else recent_revenue
    trend = 1.0 if previous_revenue <= 0 else min(1.30, max(0.75, recent_revenue / previous_revenue))
    daily_revenue = max(0.0, recent_revenue * trend)

    recent_orders = sum(item["paid_orders"] for item in recent) / max(1, len(recent))
    daily_orders = max(0, round(recent_orders * trend))
    return [daily_revenue, daily_revenue * 7, daily_revenue * 30, daily_orders, daily_orders * 7, daily_orders * 30]


def train_or_fallback(rows):
    features, targets = build_dataset(rows)
    if len(features) < 5:
        return None, heuristic_forecast(rows), False, len(features)

    try:
        from sklearn.ensemble import RandomForestRegressor

        model = RandomForestRegressor(
            n_estimators=250,
            random_state=42,
            min_samples_leaf=1,
            n_jobs=-1,
        )
        model.fit(features, targets)
        prediction = model.predict(latest_features(rows))[0].tolist()
        return model, prediction, True, len(features)
    except Exception as exc:
        print(f"RandomForest indisponible, fallback metadata: {exc}")
        return None, heuristic_forecast(rows), False, len(features)


def clean_number(value):
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return 0
    return max(0, value)


def main():
    args = parse_args()
    dataset_path = Path(args.dataset)
    artifact_dir = Path(args.artifact_dir)
    artifact_dir.mkdir(parents=True, exist_ok=True)

    rows = load_series(dataset_path)
    model, prediction, trained, sample_count = train_or_fallback(rows)
    model_path = artifact_dir / MODEL_FILE
    metadata_path = artifact_dir / METADATA_FILE

    if model is not None:
        with open(model_path, "wb") as handle:
            pickle.dump(model, handle)
    elif not model_path.exists():
        with open(model_path, "wb") as handle:
            pickle.dump({"trained": False, "reason": "insufficient_data_or_missing_sklearn"}, handle)

    metadata = {
        "trained": trained,
        "algorithm": "RandomForestRegressor" if trained else "heuristic_fallback",
        "trained_at": datetime.now().isoformat(timespec="seconds"),
        "sample_count": sample_count,
        "feature_windows_days": list(WINDOWS),
        "model_path": str(model_path),
        "dataset_path": str(dataset_path),
        "next_day_revenue": round(clean_number(float(prediction[0])), 2),
        "next_7_days_revenue": round(clean_number(float(prediction[1])), 2),
        "next_30_days_revenue": round(clean_number(float(prediction[2])), 2),
        "next_day_orders": int(round(clean_number(float(prediction[3])))),
        "next_7_days_orders": int(round(clean_number(float(prediction[4])))),
        "next_30_days_orders": int(round(clean_number(float(prediction[5])))),
    }
    with open(metadata_path, "w", encoding="utf-8") as handle:
        json.dump(metadata, handle, ensure_ascii=True, indent=2)

    print(f"Modele: {model_path}")
    print(f"Metadata: {metadata_path}")
    print("Source:", "ML entraine" if trained else "Fallback")


if __name__ == "__main__":
    main()
